version: "3"
services:
  database:
    image: postgres:14-bullseye
    
    environment:
      POSTGRES_PASSWORD: masterkey
      PGDATA: /var/lib/postgresql/data/secretary/
    ports:
      - "45432:5432"
    volumes: 
      - "./database/init-db/:/docker-entrypoint-initdb.d"